# Generated by Django 3.2.7 on 2023-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('student', 'Ученик'), ('parent', 'Родитель')], max_length=20, verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
