# Generated by Django 3.2.7 on 2023-11-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
    ]
