# Generated by Django 3.2.7 on 2023-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_application_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
    ]
