# Generated by Django 3.2.7 on 2023-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_application_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Максимальное число учеников'),
        ),
    ]
